name: "dbt_project"
version: "1.0.0"
config-version: 2

profile: "dbt_project"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    # Config indicated by + and applies to all files under models/example/
    brt_data:
      +materialized: view
